### PR TITLE
None behavior for pydantic validator

### PR DESCRIPTION
**Pull request by matin**
Pydantic changed the behavior of how it validates `None`: https://github.com/samuelcolvin/pydantic/pull/803

`setup.py` was missing a comma when specifying the version of Pydantic (`'pydantic>=0.31.1<0.32.0',`), which led to the latest version of Pydantic being used—along with the breaking change.

This PR also removes `pycodestyle` in favor of validation with `isort` + `black` + `flake8`.

Thanks to @daninfpj for catching this bug!

### CODE REVIEW

**Comment by daninfpj** [comment]
I can confirm this works, however, I think it is only by coincidence.

`each_item` is meant to be applied to collections (see [docs](https://pydantic-docs.helpmanual.io/usage/validators/#pre-and-per-item-validators) and [examples](https://github.com/samuelcolvin/pydantic/blob/master/docs/examples/validators_pre_item.py)). Even if it fixes the issue here, `cuentaBeneficiario`, `cuentaOrdenante`, etc. are not collections (`List`, `Dict`, `Set`…) so in theory `each_item` shouldn’t be applied to them, from my understanding. 🤔

**Comment by matin** [comment]
Hey @samuelcolvin,

Your change in https://github.com/samuelcolvin/pydantic/pull/803 means that field validators are now run—even if the value of the field is `None`.

This PR proposes one solution. #43 proposes another. Any preference or recommendations on another solution?

Setting `each_item=True` for the validator also solves the error; though, it doesn't appear that was the intended use.

Thanks!

**Comment by samuelcolvin** [comment]
without going into detail, I suspect the solution is `each_item=True`.

Previously the default was `whole=False` which is equivalent of `each_item=True`, thus to keep the same behaviour you'll need to use `each_item=True`.

**Comment by daninfpj** [comment]
> without going into detail, I suspect the solution is `each_item=True`.
> 
> Previously the default was `whole=False` which is equivalent of `each_item=True`, thus to keep the same behaviour you'll need to use `each_item=True`.

@samuelcolvin Thanks for your reply, Samuel! But it raises further questions…

Isn’t `each_item` meant to be used in fields that are collections? In this case, the problem is that there is an optional string that has a validator added and `pydantic` tries to run the validator on the optional field when it is empty. You’d expect `None` to be a valid value for that field, and it shouldn’t run additional validators on it.

I’m not convinced about the `each_item` solution for an optional string field. What does `each_item` mean in the case of a string?

**Comment by samuelcolvin** [comment]
sorry, I didn't look into it in much deal.

Please could you ask the question on pydantic's issue tracker so potentially others can answer and everyone can make use of the response.

Also it would help me to have a short, self-contained example to work with.

**Comment by matin** [comment]
@samuelcolvin makes sense. thanks!

**Comment by matin** [comment]
@daninfpj I merged and released the change to fix the bug. If you find a better solution, please let me know. I agree that `each_item` may not be the optimal path.

Feel free to create an issue in the meantime and link it to the issue in pydantic's gh repo.

**Pull request merged**
