### PR TITLE
fix: fix generated string to sign with zero values

### PR DESCRIPTION
**Pull request by froysm**
Closes cuenca-mx/stpmex-python#145

## Description

Fixes an issue where the string-to-sign and signature generated would be wrong when a parameter value is `0`.

## How Has This Been Tested?

We've added a failing test (`test_registra_orden_with_prioridad_0`) and tested the example request in the issue.

### CODE REVIEW

**Comment by matin** [comment]
@froysm sorry for the slow response.

Checking why this isn't breaking for us in prod. This PR undoes the change to `auth.py` in #92

**Comment by matin** [comment]
@froysm can you make the following changes to the PR?

- [ ] update the cassette from [`test_registra_orden`](https://github.com/cuenca-mx/stpmex-python/blob/main/tests/resources/cassettes/test_registra_orden.yaml). It's not out of date
- [ ] bump the library version to `3.7.3` (or give me access to your branch to do so)?
- [ ] rebase `main`

With the cassette for `test_registra_orden` updated, is the new test necessary? The default `prioridad` is `Prioridad.normal.value`, which is `0`.

**Comment by froysm** [comment]
> @froysm can you make the following changes to the PR?
> 
> * [ ]  update the cassette from [`test_registra_orden`](https://github.com/cuenca-mx/stpmex-python/blob/main/tests/resources/cassettes/test_registra_orden.yaml). It's now out-of-date
> * [ ]  bump the library version to `3.7.3` (or give me access to your branch to do so)?
> * [ ]  rebase `main`
> 
> Once the cassette for `test_registra_orden` is updated, is the new test necessary? The default `prioridad` is `Prioridad.normal.value`, which is `0`.

Sorry for the delay, been a bit away for the holidays haha.

I'm getting this PR ready for merge, but when updating the cassette for `test_registra_orden` stp answered with:

```
stpmex.exc.AccountDoesNotExist: AccountDoesNotExist(descripcionError='La cuenta {646180110400000007} no existe o no pertenece a la empresa {TAMIZI}', id=-7)
```

Is it ok if I update the fixture `orden_dict` with a clabe from the correct company (apparently something like `646180157000000004` might work) ?

**Comment by matin** [comment]
Works for me

**Comment by froysm** [comment]
@matin Seems like everything is ready!

- [x] update the cassette from test_registra_orden. It's now out-of-date
- [x] bump the library version to 3.7.3 (or give me access to your branch to do so)?
- [x] rebase main

**Review by matin — APPROVED** [review]

**Comment by matin** [comment]
@froysm looks good!

@ricardo8990 can you check why GH actions aren't running? Whenever the tests pass, this is ready to merge and release

**Pull request merged**
