### PR TITLE
Exceptions2

### LINKED ISSUE #66: corregir código de error InvalidRfcOrCurp
STP usa el  id = 0 para distintos mensajes de error. Cuando hay errores generales con ese Id se crea una excepción de tipo `InvalidRfcOrCurp`.

### LINKED ISSUE #71: add id: -22 error code
add new error code:
StpmexException(descripcionError='La cuenta CLABE {....} no coincide para la institucion operante {40072}', id=-22)

```
{
resultado: {
descripcionError: 'La cuenta CLABE {...} no coincide para la institucion operante {40072}', 
id: -22
}
}
```

### LINKED ISSUE #72: add id: -34
{
resultado: {
descripcionError: 'Clave rastreo invalida : ....', 
id: -34
}
}

### LINKED ISSUE #77: add id=-24
create exception for: `descripcionError='Cuenta {6461801570XXXXXXXX} - {MISMA_CUENTA}', id=-24`

### LINKED ISSUE #82: add id=-9
descripcionError='La Institucion 90679 no es valida', id=-9

### PR DESCRIPTION
**Pull request by felipaoo**
closes #77 
closes #71 
closes #72 
closes #66 
closes #82 

y algunos otros

### CODE REVIEW

**Comment by matin** [comment]
merge after #74

**Comment by matin** [comment]
@felipaoo  how's this coming along? Any updates on the mocks?

**Comment by felipaoo** [comment]
I found a way to pass parameters to a fixture in order to generate mocks for each exception. But, I'm not sure if readable. Any feedback?

**Comment by matin** [comment]
Looks good. Just bump to `3.5.0` since it's a breaking change

**Comment by matin** [comment]
> Looks good. Just bump to `3.5.0` since it's a breaking change

@felipaoo

**Pull request merged**
