### PR TITLE
remove CuentaFisica.update()

### PR DESCRIPTION
**Pull request by matin**
STP made a ridiculous breaking change where you can no longer do dar de baja and dar de alta on the same CLABE. They decided not to let anyone know about this change.

The code being removed no longer works.

### CODE REVIEW

**Comment by matin** [comment]
@felipaoo any idea why `make lint` is failing? It passes locally

**Comment by alexviquez** [comment]
@matin  Revisa si tienes las versiones de flake correctas en
 https://github.com/cuenca-mx/stpmex-python/blob/master/setup.py#L22
Flake hizo un update y ya no corre lint
flake8==3.7.9
isort>=4.3.21,<4.4
black>=19.10b0,<20.0
mypy>=0.770

**Comment by matin** [comment]
@alexviquez puedes actualizar?

**Comment by alexviquez** [comment]
Lo hago

**Pull request merged**
